# This file was generated by the {rix} R package v0.12.0 on 2024-09-21
# with following call:
# >rix::rix(r_ver = "6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212",
#  > r_pkgs = project_pkgs,
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "code",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses nixpkgs' revision 6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212 for reproducibility purposes
# which will install R version 4.4.0.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      conflicted
      dotenv
      dplyr
      forcats
      ggplot2
      ggtext
      languageserver
      readr
      tarchetypes
      targets
      tidyr;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages   ];
  
}
